---

- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ public_ip_address_name }}"
    allocation_method: "{{ public_ip_address_allocation_method }}"
    domain_name: "{{ public_ip_address_domain_name }}"
  tags:
    - public_ip